-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 00:03:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mebelorg_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mebelorg_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mebelorg_db` DEFAULT CHARACTER SET utf8 ;
USE `mebelorg_db` ;

-- -----------------------------------------------------
-- Table `mebelorg_db`.`roli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`roli` (
  `id_roli` INT NOT NULL AUTO_INCREMENT,
  `nazvanie_roli` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_roli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`polzovateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`polzovateli` (
  `id_polzovateli` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `parol` VARCHAR(100) NOT NULL,
  `id_roli` INT NOT NULL,
  PRIMARY KEY (`id_polzovateli`),
  INDEX `fk_polzovateli_roli_idx` (`id_roli` ASC) VISIBLE,
  CONSTRAINT `fk_polzovateli_roli`
    FOREIGN KEY (`id_roli`)
    REFERENCES `mebelorg_db`.`roli` (`id_roli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`kategorii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`kategorii` (
  `id_kategorii` INT NOT NULL AUTO_INCREMENT,
  `nazvanie_kategorii` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_kategorii`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`proizvoditeli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`proizvoditeli` (
  `id_proizvoditeli` INT NOT NULL AUTO_INCREMENT,
  `nazvanie_proizvoditeli` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_proizvoditeli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`postavshiki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`postavshiki` (
  `id_postavshiki` INT NOT NULL AUTO_INCREMENT,
  `nazvanie_postavshiki` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_postavshiki`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`tovari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`tovari` (
  `id_tovari` INT NOT NULL AUTO_INCREMENT,
  `artikul` VARCHAR(20) NOT NULL,
  `nazvanie_tovara` VARCHAR(255) NOT NULL,
  `edinica_izmereniya` VARCHAR(50) NOT NULL,
  `tsena` DECIMAL(10,2) NOT NULL,
  `id_postavshiki` INT NOT NULL,
  `id_proizvoditeli` INT NOT NULL,
  `id_kategorii` INT NOT NULL,
  `skidka` INT NOT NULL,
  `kolichestvo_na_sklade` INT NOT NULL,
  `opisanie` TEXT(100) NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tovari`),
  UNIQUE INDEX `artikul_UNIQUE` (`artikul` ASC) VISIBLE,
  INDEX `fk_tovari_kategorii_idx` (`id_kategorii` ASC) VISIBLE,
  INDEX `fk_tovari_proizvoditeli_idx` (`id_proizvoditeli` ASC) VISIBLE,
  INDEX `fk_tovari_postavshiki_idx` (`id_postavshiki` ASC) VISIBLE,
  CONSTRAINT `fk_tovari_kategorii`
    FOREIGN KEY (`id_kategorii`)
    REFERENCES `mebelorg_db`.`kategorii` (`id_kategorii`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tovari_proizvoditeli`
    FOREIGN KEY (`id_proizvoditeli`)
    REFERENCES `mebelorg_db`.`proizvoditeli` (`id_proizvoditeli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tovari_postavshiki`
    FOREIGN KEY (`id_postavshiki`)
    REFERENCES `mebelorg_db`.`postavshiki` (`id_postavshiki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`punkti_vidachi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`punkti_vidachi` (
  `id_punkti_vidachi` INT NOT NULL AUTO_INCREMENT,
  `adres` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_punkti_vidachi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`statusi_zakazov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`statusi_zakazov` (
  `id_statusi_zakazov` INT NOT NULL AUTO_INCREMENT,
  `nazvanie_statusa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_statusi_zakazov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`zakazi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`zakazi` (
  `id_zakazi` INT NOT NULL AUTO_INCREMENT,
  `data_zakaza` DATE NOT NULL,
  `data_dostavki` DATE NOT NULL,
  `id_punkti_vidachi` INT NOT NULL,
  `id_klient` INT NOT NULL,
  `kod_polucheniya` INT NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_zakazi`),
  INDEX `fk_zakazi_statusi_idx` (`id_status` ASC) VISIBLE,
  INDEX `fk_zakazi_punkti_vidachi_idx` (`id_punkti_vidachi` ASC) VISIBLE,
  INDEX `fk_zakazi_polzovateli_idx` (`id_klient` ASC) VISIBLE,
  CONSTRAINT `fk_zakazi_statusi`
    FOREIGN KEY (`id_status`)
    REFERENCES `mebelorg_db`.`statusi_zakazov` (`id_statusi_zakazov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zakazi_punkti_vidachi`
    FOREIGN KEY (`id_punkti_vidachi`)
    REFERENCES `mebelorg_db`.`punkti_vidachi` (`id_punkti_vidachi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zakazi_polzovateli`
    FOREIGN KEY (`id_klient`)
    REFERENCES `mebelorg_db`.`polzovateli` (`id_polzovateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mebelorg_db`.`sostav_zakaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mebelorg_db`.`sostav_zakaza` (
  `id_sostav_zakaza` INT NOT NULL AUTO_INCREMENT,
  `id_zakazi` INT NOT NULL,
  `id_tovara` INT NOT NULL,
  `kolichestvo` INT NOT NULL,
  PRIMARY KEY (`id_sostav_zakaza`),
  INDEX `fk_sostav_zakaza_zakazi_idx` (`id_zakazi` ASC) VISIBLE,
  INDEX `fk_sostav_zakaza_tovari_idx` (`id_tovara` ASC) VISIBLE,
  CONSTRAINT `fk_sostav_zakaza_zakazi`
    FOREIGN KEY (`id_zakazi`)
    REFERENCES `mebelorg_db`.`zakazi` (`id_zakazi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sostav_zakaza_tovari`
    FOREIGN KEY (`id_tovara`)
    REFERENCES `mebelorg_db`.`tovari` (`id_tovari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
